apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.api.name }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.port }}
  type: {{ .Values.api.service.type }}
