{{- if .Values.azureKeyVaultCSI }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname
  namespace: {{ .Values.global.namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "{{ .Values.azureKeyVaultCSI.userAssignedIdentityID }}"
    keyvaultName: "{{ .Values.azureKeyVaultCSI.name }}"
    clientID: "{{ .Values.azureKeyVaultCSI.clientID }}"
    tenantId: "{{ .Values.azureKeyVaultCSI.tenantId }}"
    objects: |
      array:
        {{- range .Values.azureKeyVaultCSI.secrets }}
        - |
          objectName: {{ .objectName }}
          objectType: {{ .objectType }}
        {{- end }}
    secretObjects: |
      - secretName: braintrust-secrets
        type: Opaque
        data:
          {{- range .Values.azureKeyVaultCSI.secrets }}
          - |
          objectName: {{ .objectName }}
          objectType: {{ .objectType }}
        {{- end }}
{{- end }}
